spring:
    main:
        banner-mode: off
    datasource:
        url: jdbc:h2:mem:logmetrixdb;MODE=LEGACY;
        username: sa
        password:
    h2:
        console.enabled: true
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: none
jwt:
    token-validity-seconds: 86400                
    base64-secret: MzMzYjg3YTRmYmU0YmM4YzJkZWE4NTJlZGEzMDgzZjkzOWNjM2MwMWQ4NzI2MjgwZWU0MzM5ZTY0MGEzMjg1YzIwMjU1MWM5ZTNkMzg5YWNiMjExNGJlMTE4NjZlMWMxODIxNjYwMTBkZTRiZWRlNzU3MDc5ZThhMDcxMjlkMGE
